FROM node:22-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY frontend/ .

# Construir la aplicación para producción
RUN npm run build

# Etapa de producción
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

