services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromService:
          type: web
          name: backend
          property: host
